//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkers.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Checkers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Column: .
        /// </summary>
        internal static string GameWithAiViewModel_Button_Click__Column {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_Button_Click__Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Row: .
        /// </summary>
        internal static string GameWithAiViewModel_Button_Click__Row {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_Button_Click__Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckMove: False.
        /// </summary>
        internal static string GameWithAiViewModel_CheckMove_CheckMove__False {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_CheckMove_CheckMove__False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckMoveBlack: False.
        /// </summary>
        internal static string GameWithAiViewModel_CheckMoveBlack_CheckMoveBlack__False {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_CheckMoveBlack_CheckMoveBlack__False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckMoveWhite: False.
        /// </summary>
        internal static string GameWithAiViewModel_CheckMoveWhite_CheckMoveWhite__False {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_CheckMoveWhite_CheckMoveWhite__False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , col=.
        /// </summary>
        internal static string GameWithAiViewModel_MakeMove_col {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_MakeMove_col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piece1 : row=.
        /// </summary>
        internal static string GameWithAiViewModel_MakeMove_P1_row {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_MakeMove_P1_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piece2 : row=.
        /// </summary>
        internal static string GameWithAiViewModel_MakeMove_P2_row {
            get {
                return ResourceManager.GetString("GameWithAiViewModel_MakeMove_P2_row", resourceCulture);
            }
        }
    }
}
